import { writeFileSync } from 'node:fs';
import path from 'node:path';

import chalk from 'chalk';
import { addCoverageReport } from 'monocart-reporter';
import { expect } from '@playwright/test';
import slugifier from '@sindresorhus/slugify';

export const outputDir = path.join(import.meta.dirname, 'out');

export function withHtml(htmlBody, testBody) {
  return async function ({ page }, testInfo) {
    const htmlFile = `${slugify(testInfo.title)}.html`;
    const htmlContent = `
      <!DOCTYPE html><!-- autogenerated -->
      <html>
        <head>
          <title>${testInfo.title}</title>
          <link rel="icon" href="data:,">
          <link rel="stylesheet" href="../assets/simple.min.css"/>
          <script src="../assets/init-zjax.js"></script>
        </head>
        <body>
          <main>${htmlBody}</main>
        </body>
      </html>
    `;
    writeFileSync(path.join(outputDir, htmlFile), htmlContent, 'utf-8');

    page.console = {};
    page.on('console', msg => {
      const type = msg.type();
      if (!page.console[type])
        page.console[type] = [];
      page.console[type].push(msg.text());
    });
    
    await runTest(page, htmlFile, testBody, testInfo);
  };
}

async function runTest(page, htmlFile, testBody, testInfo) {
  await page.coverage.startJSCoverage({ resetOnNavigation: false });
  await page.goto(`/test/out/${htmlFile}`);
  await testBody(page);
  const coverageData = await page.coverage.stopJSCoverage();
  await addCoverageReport(coverageData, testInfo);
}

export async function expectDialogAfter(page, action, dialogType, respondWith) {
  return Promise.all([
    page.waitForEvent('dialog').then(async (dialog) => {
      expect(dialog.type()).toBe(dialogType);
      await dialog[respondWith]();
      return dialog;
    }),
    action(page),
  ]);
}

export function expectConsoleEventAfter(page, action) {
  return Promise.all([
    page.waitForEvent('console'),
    action(page),
  ]);
}

export function slugify(string) {
  return slugifier(string, {
    customReplacements: [
      ['*', 'star'],
      ['/', '-or-'],
      ['->', '-to-'],
    ]
  });
}

export default class {
  onTestEnd(test, result) {
    if (result.status !== 'passed') {
      console.error('⚠️', chalk.bgRed(`test/out/${slugify(test.title)}.html`));
    }
  }

  onEnd() {
    console.log('coverage report:', chalk.cyan('open test/result/report/coverage/index.html'));
  }
}
